---
# handlers file for host_preparation
- name: Disable repos
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable foundational repos
  rhsm_repository:
    name: "{{ item }}"
  loop: "{{ repositories }}"

- name: Reboot nodes
  reboot:
