---
- name: Ensure firewalld is installed
  dnf:
    name: firewalld
    state: present

- name: Ensure firewalld services is enabled and running
  systemd:
    name: firewalld
    state: started
    enabled: yes
