---
- name: Register nodes
  redhat_subscription:
    state: present
    username: "{{ rhcp_username }}"
    password: "{{ rhcp_password }}"
  notify:
    - Disable repos
    - Enable foundational repos
