---
- name: Enable required repositories by Ceph
  rhsm_repository:
    name: "{{ item }}"
  loop: "{{ ceph_repositories }}"

- name: Ensure the required packages are installed
  dnf:
    name: "{{ required_rpms }}"
    state: present

- name: Create inventory file to be used by preflight playbook
  template:
    src: templates/inventory
    dest: /usr/share/cephadm-ansible/inventory
    owner: root
    group: root
    mode: '0644'
