---
- name: Enable required repositories by Ceph
  rhsm_repository:
    name: "{{ item }}"
  loop: "{{ ceph_repositories }}"
  when: ansible_facts['hostname'] == 'node01'

- name: Ensure the required packages are installed
  dnf:
    name: "{{ required_rpms }}"
    state: present
  when: ansible_facts['hostname'] == 'node01'

- name: Create inventory file to be used by preflight playbook
  template:
    src: templates/inventory
    dest: /usr/share/cephadm-ansible/inventory
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['hostname'] == 'node01'

- name: Generate ssh key pair
  user:
    name: root
    generate_ssh_key: yes
  when: ansible_facts['hostname'] == 'node01'

- name: Get ssh public key
  fetch:
    src: /root/.ssh/id_rsa.pub 
    dest: files/
    flat: yes
  when: ansible_facts['hostname'] == 'node01'

- name: Insert public key into authorized keys
  blockinfile:
    path: /root/.ssh/authorized_keys
    block: "{{ lookup('file','files/id_rsa.pub') }}"
    insertafter: EOF

- name: Execute preflight.yml playbook
  shell: ansible-playbook -i /usr/share/cephadm-ansible/inventory /usr/share/cephadm-ansible/cephadm-preflight.yml -e "ceph_origin=rhcs" -u root -v | tee ~/ansible.log
  when: ansible_facts['hostname'] == 'node01'
  tags: preflight

- name: Ensure versions are updated
  dnf:
    name: '*'
    state: latest
  notify:
  - Reboot nodes
